### PR TITLE
Track purge_det

### LINKED ISSUE #131: Track progress of purge_det
Similar to that which has been implemented for `gudrun_dcs`, the `progressBar` should track the progress of `purge_det`.

### PR DESCRIPTION
**Pull request by jswift-stfc**
PR addressing the issue of tracking the progress of `purge_det` using the progress bar. This seems to be working, however could do with some testing to see how accurate/consistent it is.
Closes #131.

### CODE REVIEW

**Comment by trisyoungs** [comment]
Making progress.  This now tracks the purge through the raw files, but there is a significant period at the beginning where something is happening, but it is not being tracked.  Have to look in to the exact output of purge_det to make a suggestion on what else to capture here...

**Comment by jswift-stfc** [comment]
> Making progress. This now tracks the purge through the raw files, but there is a significant period at the beginning where something is happening, but it is not being tracked. Have to look in to the exact output of purge_det to make a suggestion on what else to capture here...

It looks like it first does something with the specified groups file. I'll add a check for that, and see if it smooths it out a bit.

**Review by trisyoungs — APPROVED** [review]
Now get some "preliminary" indication of progress, but there's a big pause after that before the final "splurt" of progress happens.  However, this may just be a delay in windows, as on Linux I don't really see that. 

So, :+1:!

**Comment by jswift-stfc** [comment]
Something to remember when we come back to finalising this feature!

**Pull request merged**
