### PR TITLE
Generic fixes

### LINKED ISSUE #215: Plotting when running a single sample
When a single sample is ran and eventually plotted, the RDF plot does not work.

### PR DESCRIPTION
**Pull request by jswift-stfc**
Various bug fixes and minor enhancements.
Notable enhancements are that the suggested tweak factor is now shown in the GUI, and instrument configurations have been added which can be loaded and used (although for now, NIMROD is the only stable one).

Closes #215.

### CODE REVIEW

**Comment by trisyoungs** [comment]
A crash!

```
  File "main.py", line 5, in <module>
  File "src\gui\gudpy.py", line 23, in main
  File "src\gui\gudpy.py", line 10, in __init__
  File "src\gui\gudpy.py", line 16, in initComponents
  File "src\gui\widgets\main_window.py", line 113, in __init__
  File "src\gui\widgets\main_window.py", line 315, in initComponents
AttributeError: 'PySide6.QtWidgets.QMainWindow' object has no attribute 'new_'
[11800] Failed to execute script 'main' due to unhandled exception!
```

**Review by trisyoungs — CHANGES_REQUESTED** [review]
Lots of nice new stuff in here.  I noticed a couple of small things:

1. I think that locating the "Suggested Tweak Factor" label and value underneath the DCS / level percentage would look better - at the minute the variability in the tweak factor value keeps resizing the whole right-hand panel.
2. Choosing the "New" option doesn't clear any data displayed on the "Plots" tab.

**Comment by jswift-stfc** [comment]
Probably makes more sense that way. I shall fix the second point. A non-related question, but I think you said the other day that you would expect the output files to be produced in the directory of the original input file, is that right? Currently they are produced where GudPy is being run.

**Comment by trisyoungs** [comment]
I would expect that only based on accepted behaviour of the original GudrunGUI.  It also feels sensible to have the output generated in the same directory as the input!

**Comment by jswift-stfc** [comment]
It does make more sense. I'll add that to this PR.

**Pull request merged**
