### PR TITLE
Refactor charts

### LINKED ISSUE #219: Plot beam profile
The beam profile controls (list of "intensity values") don't often get changed, but it would be nice to provide a more graphical feedback on what these values actually represent.  A simple plot with perhaps a polygonal area series might do the trick.

### PR DESCRIPTION
**Pull request by jswift-stfc**
This PR refactors the chart/plotting system of GudPy.

Previously, a single file controlled all of the charting related stuff - "gudpy_charts.py". This has now been split up into multiple scripts and classes - to be more modular and ultimately easier to manage/modify.

Also included in this PR is the plotting of the beam intensity values.

Closes #219.

### CODE REVIEW

**Review by trisyoungs — CHANGES_REQUESTED** [review]
Splitting up of the original charting looks good.  I noticed a few small things:

1. Beam profile plot needs an x axis and title ("Beam X, cm")
2. Adding a new beam profile value to the table promotes a colour change in the profile plot, perhaps indicating that new series are being added all the time.
3. Changing a beam profile value in the table doesn't update the plot.

And the old zooming bug (always shows full X-axis) appears to be back...

**Comment by jswift-stfc** [comment]
I totally forgot to add the zoom functionality!!

**Review by trisyoungs — APPROVED** [review]
It works! :)

**Comment by jswift-stfc** [comment]
Yes!

**Pull request merged**
