### PR TITLE
Build Singularity image

### LINKED ISSUE #273: Singularity Image
For distributing to Linux, we should build a singularity image, to be compatible with more Linux platforms. Since currently, we include glibc from Ubuntu 20.04, which is not compatible with older versions of Linux.

### PR DESCRIPTION
**Pull request by jswift-stfc**
This PR builds a .sif (Singularity Image File), which can be run using `singularity run`. This image uses Ubuntu 20.04, and aims to resolve dependancy problems with running GudPy across different versions of ubuntu, and flavours of linux. However, the final artifact has not yet been tested.

Closes #273.

### CODE REVIEW

**Comment by jswift-stfc** [comment]
As of 915e62f390e1a6b3b9e15c38515cf7b228cb5fdf, the sif produced is working as expected. This was achieved by downgrading to singularity version 2.5.2, and making the container writable. As a consequence of this, however, the size of the produced sif has skyrocketed to just under `2GB`.. Going to see if it's possible to reduce this.

**Review by trisyoungs — COMMENTED** [review]
I'm afraid this still doesn't quite work correctly for me - I can run Gudrun, but it stops prematurely:
Screenshot from 2022-01-12 09-31-57

I don't think that 2Gb is an acceptable size for our users to download. It would be OK for IDAaaS, but for the poor university student at home who wants to run it on their laptop it's a bit much.

**Comment by jswift-stfc** [comment]
> I'm afraid this still doesn't quite work correctly for me - I can run Gudrun, but it stops prematurely: Screenshot from 2022-01-12 09-31-57
> 
> I don't think that 2Gb is an acceptable size for our users to download. It would be OK for IDAaaS, but for the poor university student at home who wants to run it on their laptop it's a bit much.

That's strange that it doesn't work for you, I pulled the artifact and it worked on my linux partition. The premature stopping will be due to lack of permissions to write to `/opt/GudPy/bin/StartupFiles` when Gudrun tries to write the group calibration file. I agree 2GB is way too big. I guess the next idea would be to mount the entire GudPy as a persistent overlay? Or I wonder if it would be enough to do that with the StartupFiles directory, and symlink it to `/opt/GudPy/bin/StartupFiles`?

**Comment by trisyoungs** [comment]
I think just an overlay for StartupFiles will be enough. That's the important one.

**Comment by jswift-stfc** [comment]
> > I'm afraid this still doesn't quite work correctly for me - I can run Gudrun, but it stops prematurely: Screenshot from 2022-01-12 09-31-57
> > I don't think that 2Gb is an acceptable size for our users to download. It would be OK for IDAaaS, but for the poor university student at home who wants to run it on their laptop it's a bit much.
> 
> That's strange that it doesn't work for you, I pulled the artifact and it worked on my linux partition. The premature stopping will be due to lack of permissions to write to `/opt/GudPy/bin/StartupFiles` when Gudrun tries to write the group calibration file. I agree 2GB is way too big. I guess the next idea would be to mount the entire GudPy as a persistent overlay? Or I wonder if it would be enough to do that with the StartupFiles directory, and symlink it to `/opt/GudPy/bin/StartupFiles`?

Also noticed you are using the "View Previous Output" option :D

**Pull request merged**
